name = "www"
pages_build_output_dir = ".vercel/output"

[build]
command = "npm run build"
cwd = "./"

[compatibility_date]
compatibility_date = "2024-01-01"

[compatibility_flags]
compatibility_flags = ["nodejs_compat"]
